# Generated by Django 4.2.30 on 2026-05-20 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('department', models.CharField(blank=True, max_length=80)),
                ('organization_id', models.CharField(default='ORG001', max_length=40)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee')], default='employee', max_length=10)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='employee_set', related_query_name='employee', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='employee_set', related_query_name='employee', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Employee',
                'ordering': ['employee_id'],
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('salary_type', models.CharField(choices=[('fixed_monthly', 'Fixed Monthly'), ('daily_wage', 'Daily Wage'), ('hourly', 'Hourly')], default='fixed_monthly', max_length=20)),
                ('currency', models.CharField(default='UGX', max_length=5)),
                ('working_days', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salary',
            },
        ),
        migrations.CreateModel(
            name='DailyQRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qr_type', models.CharField(choices=[('arrival', 'Arrival'), ('departure', 'Departure'), ('registration', 'Registration')], max_length=15)),
                ('date', models.DateField()),
                ('token', models.CharField(max_length=64, unique=True)),
                ('organization_id', models.CharField(default='ORG001', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Daily QR Code',
                'unique_together': {('qr_type', 'date', 'organization_id')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyPayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('working_days', models.PositiveIntegerField(default=30)),
                ('days_present', models.PositiveIntegerField(default=0)),
                ('days_absent', models.PositiveIntegerField(default=0)),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('final_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='UGX', max_length=5)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Payroll',
                'ordering': ['-year', '-month'],
                'unique_together': {('employee', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('clock_in_time', models.DateTimeField(blank=True, null=True)),
                ('clock_out_time', models.DateTimeField(blank=True, null=True)),
                ('clock_in_lat', models.FloatField(blank=True, null=True)),
                ('clock_in_lng', models.FloatField(blank=True, null=True)),
                ('clock_out_lat', models.FloatField(blank=True, null=True)),
                ('clock_out_lng', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('incomplete', 'Incomplete')], default='incomplete', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
